calculation: single
T_MIN: 0
NT: 101
DT: 10
DT_SAMPLE: 10
NTV: 101
DELTA_P: 0.1
DELTA_P_SAMPLE: 1
input: input
P_MIN: 0
high_verbosity: true
calculate:
    - F
    - G
    - U
    - H
    - V
    - alpha
    - gamma
    - Cp
    - Cv
    - Bt
    - Btp
    - Bs
energy_unit: ry
# plot_results: true
output_directory: ./results/
