calculation: different phonon dos
NT: 401
DT: 1
DT_SAMPLE: 1
P_MIN: 0
T_MIN: 0
NTV: 701
DELTA_P: 0.1
DELTA_P_SAMPLE: 1
order: 3
# static_only: true
input:
    input_01: 6
    input_02: 96
    input_03: 96
    input_04: 24
    input_05: 24
    input_06: 192
    input_07: 384
    input_08: 24
    input_09: 384
    input_10: 96
    input_11: 192
    input_12: 384
    input_13: 48
    input_14: 96
    input_15: 48
    input_16: 96
    input_17: 96
    input_18: 384
    input_19: 384
    input_20: 48
    input_21: 384
    input_22: 96
    input_23: 384
    input_24: 96
    input_25: 192
    input_26: 192
    input_27: 192
    input_28: 384
    input_29: 192
    input_30: 192
    input_31: 96
    input_32: 192
    input_33: 192
    input_34: 384
    input_35: 384
    input_36: 192
    input_37: 24
    input_38: 48
    input_39: 96
    input_40: 48
    input_41: 384
    input_42: 12
    input_43: 96
    input_44: 48
    input_45: 192
    input_46: 12
    input_47: 96
    input_48: 48
    input_49: 6
    input_50: 96
    input_51: 24
    input_52: 24
calculate:
    - F
    - G
    - U
    - H
    - V
    - alpha
    - gamma
    - Cp
    - Cv
    - Bt
    - Btp
    - Bs
energy_unit: ry
output_directory: ./results/
high_verbosity: true
